In [2]:
#input of the equation
equation_inputs = [4, -2, 3.5, 5, -11, -4.7]

#number of the weights we are looking to optimize
num_weights = 6

In [3]:
import numpy as py

sol_per_pop = 8
#defining the population size

pop_size = (sol_per_pop, num_weights) 
#the population will have sol_per_pop chromosome where each chromosome has num_weights genes

#Creating the initial population
new_population = py.random.uniform(low = -4.0, high = 4.0, size = pop_size)

new_population

array([[ 0.17070453, -0.93276964,  1.1660038 ,  3.78419896,  3.48702156,
         0.71122733],
       [ 2.52534209,  1.02901947, -3.98989274, -1.32101462,  1.05752491,
        -3.79364782],
       [-2.85390607, -3.42714355, -3.26224655, -3.59416113, -2.41304057,
         3.02766118],
       [-2.3491131 , -2.88455323,  0.89873699, -3.0583198 , -3.31037412,
         3.31896504],
       [ 2.88247469, -1.95523755, -3.63385794, -1.19356809,  0.4386998 ,
        -1.65659121],
       [ 1.0776529 ,  2.73036682,  3.68645404,  3.24692763,  0.94312102,
         0.51188162],
       [ 0.98191308, -3.00840383, -3.07685008,  1.89542187,  3.35430237,
        -1.26415444],
       [ 0.61122964,  3.03735341, -0.50814965, -2.96219989,  3.53027438,
        -3.97311938]])

In [5]:
def cal_pop_fitness(equation_inputs, pop) :
    #calculating the fitness value of each solution in the current population
    #the fitnes function calculates the sum of produts between each input and its corresponding weight
    fitness = py.sum(pop * equation_inputs, axis = 1)
    
    return fitness

In [15]:
def select_mating_pool(pop, fitness, num_parents):
    #selecting the best individuals in the current generation as parents for producing the offspring of the next generation
    parents = py.empty((num_parents, pop.shape[1]))
    
    for parent_num in range(num_parents):
        max_fitness_idx = py.where(fitness == py.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        
        parents[parent_num, :]  = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
        
    return parents

In [16]:
def crossover(parents, offspring_size):
    offspring = py.empty(offspring_size)
    
    #the point at which crossover takes place between two parents. Usually, it is at the center.
    crossover_point = py.uint8(offspring_size[1]/2)
    
    for k in range(offspring_size[0]):
        #index of the first parent to mate
        parent1_idx = k % parents.shape[0]
        
        #index of the second parent to mate
        parent2_idx = (k + 1) % parents.shape[0]
        
        #the new offspring will have its first half of its genes taken from the first parent
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        
        #the new offspring will have its second half of its genes taken from the second parent
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
        
    return offspring

In [17]:
def mutation(offspring_crossover):
    #mutation changes a single gene on each offspring randomly
    
    for idx in range(offspring_crossover.shape[0]):
        #the random value to be added to the gene
        random_value = py.random.uniform(-1.0, 1.0, 1)
        
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
        
    return offspring_crossover

In [26]:
num_generations    = 5
num_parents_mating = 4

for generation in range(num_generations) :
    #Measuring the fitness of each chromosome in the population
    fitness = cal_pop_fitness(equation_inputs, new_population)
    
    #selecting the best parents in the population for mating
    parents = select_mating_pool(new_population, fitness, num_parents_mating)
    
    #generating next generation using crossover
    offspring_crossover = crossover(parents, offspring_size = (pop_size[0] - parents.shape[0], num_weights))
    
    #Adding some variations to the offspring using mutation
    offspring_mutation = mutation(offspring_crossover)
    
    #creating the new population based on the parents and offspring
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :]  = offspring_mutation
    
    #the bet result in the current iteration
    print('Best result : ', py.max(py.sum(new_population * equation_inputs, axis = 1)))

Best result :  57.349326813750686
Best result :  64.54650042909245
Best result :  68.30565868131995
Best result :  68.30565868131995
Best result :  70.40662460987673


In [27]:
#Getting the best solution afteriterating finishing all generations
#At first, the fitness is calculated for each solution in the final generation
fitness = cal_pop_fitness(equation_inputs, new_population)

fitness

array([68.30565868, 67.96240231, 64.94662326, 64.84815997, 70.40662461,
       58.97233659, 67.60142142, 64.81731467])

In [28]:
#then return the index of that solution corresponding to the best fitness
best_match_idx = py.where(fitness == py.max(fitness))

best_match_idx

(array([4], dtype=int64),)

In [29]:
print('Best solution : ', new_population[best_match_idx, :])
print('Best solution fitness : ', fitness[best_match_idx])

Best solution :  [[[ 1.0776529   2.73036682  3.68645404 -3.0583198  -8.14044475
    3.31896504]]]
Best solution fitness :  [70.40662461]
